export const CARDS = {
  vraag: [
    { q: "Wat is een golflengte?", opts: ["De afstand tussen twee golftoppen", "De hoogte van een golf", "Het aantal golven per seconde", "De snelheid van een golf"], ans: 0, pts: 2 },
    { q: "Hoe snel reist elektromagnetische straling door vacuüm?", opts: ["300.000 km/s", "150.000 km/s", "1.000 km/s", "De snelheid hangt af van golflengte"], ans: 0, pts: 2 },
    { q: "Welke straling heeft de kortste golflengte?", opts: ["Röntgenstraling", "Zichtbaar licht", "Infraroodstraling", "Radiogolven"], ans: 0, pts: 2 },
    { q: "Wat is de frequentie van een golf?", opts: ["Aantal golven per seconde", "Afstand tussen twee golftoppen", "Hoogte van de golf", "Snelheid van de golf"], ans: 0, pts: 2 },
    { q: "Welke kleur zichtbaar licht heeft de langste golflengte?", opts: ["Rood", "Violet", "Groen", "Geel"], ans: 0, pts: 2 },
    { q: "Wat betekent transmissie bij straling?", opts: ["Straling wordt doorgelaten", "Straling wordt weerkaatst", "Straling wordt omgezet in warmte", "Straling wordt opgeslagen"], ans: 0, pts: 2 },
    { q: "Wat betekent absorptie bij straling?", opts: ["Straling wordt opgenomen en omgezet in energie", "Straling gaat door het materiaal heen", "Straling kaatst terug", "Straling versnelt"], ans: 0, pts: 2 },
    { q: "Wat is reflectie?", opts: ["Straling kaatst terug van het oppervlak", "Straling wordt doorgeslikt", "Straling vertraagt", "Straling verandert van kleur"], ans: 0, pts: 2 },
    { q: "Infraroodstraling ervaren mensen als...", opts: ["Warmte", "Licht", "Geluid", "Trilling"], ans: 0, pts: 2 },
    { q: "De formule die golflengte, frequentie en lichtsnelheid verbindt is...", opts: ["c = λ × f", "c = λ + f", "c = λ / f", "c = f / λ"], ans: 0, pts: 3 },
    { q: "Als golflengte kleiner wordt, wordt frequentie...", opts: ["Groter", "Kleiner", "Gelijk", "Nul"], ans: 0, pts: 2 },
    { q: "Wat heb je nodig om een röntgenfoto te maken?", opts: ["Röntgenbron en detectorscherm", "Lamp en spiegel", "Thermometer en camera", "Microscoop"], ans: 0, pts: 2 },
    { q: "Waarom zijn botten wit op een röntgenfoto?", opts: ["Botten absorberen veel röntgenstraling", "Botten reflecteren licht", "Botten zijn lichter dan spieren", "Botten zenden straling uit"], ans: 0, pts: 2 },
    { q: "Waarom zijn zachte weefsels donker op een röntgenfoto?", opts: ["Ze laten röntgenstraling grotendeels door", "Ze absorberen alle straling", "Ze zijn dikker dan botten", "Ze reflecteren de straling"], ans: 0, pts: 2 },
    { q: "Röntgenstraling die geabsorbeerd wordt door weefsel kan...", opts: ["Moleculen kapot maken", "Botten sterker maken", "Pijn verlichten", "Bloed aanmaken"], ans: 0, pts: 2 },
    { q: "Hoe beschermen röntgentechnici zichzelf?", opts: ["Afstand houden of achter loden muur staan", "Zonnebril dragen", "Handschoenen aantrekken", "Bron uitzetten"], ans: 0, pts: 2 },
    { q: "Waarom is lood goed tegen röntgenstraling?", opts: ["Lood absorbeert röntgenstraling goed", "Lood is goedkoop", "Lood is licht van gewicht", "Lood reflecteert alle straling"], ans: 0, pts: 2 },
    { q: "Wat is een tracer (merkstof)?", opts: ["Radioactieve stof ingespoten die gammastraling uitzendt", "Kleurstof voor röntgenfoto's", "Röntgenbron", "Meetapparaat"], ans: 0, pts: 2 },
    { q: "Hoe werkt een gammacamera?", opts: ["Vangt gammastraling op van tracer in lichaam", "Schiet gammastraling in lichaam", "Meet temperatuurverschillen", "Meet geluidsgolven"], ans: 0, pts: 2 },
    { q: "Wat is het verschil tussen röntgenfoto en gammascan?", opts: ["Röntgen: straling van buiten; gammascan: stof in lichaam zendt zelf", "Ze zijn hetzelfde", "Gammascan gebruikt lichtstraling", "Röntgen meet alleen huid"], ans: 0, pts: 3 },
    { q: "Wat is een natuurlijk radioactieve stof?", opts: ["Van nature radioactief, in natuur aanwezig", "Door mensen radioactief gemaakt", "Een laboratoriumstof", "Een medicijn"], ans: 0, pts: 2 },
    { q: "Welke straling heeft een tracer die als gammascan gebruikt wordt?", opts: ["Gammastraling", "Zichtbaar licht", "Infraroodstraling", "Radiogolven"], ans: 0, pts: 2 },
    { q: "Röntgenstraling die dwars door lichaam gaat zonder absorptie...", opts: ["Veroorzaakt geen schade", "Beschadigt organen", "Maakt botten zichtbaar", "Wordt omgezet in warmte"], ans: 0, pts: 2 },
    { q: "Welke straling staat links van zichtbaar licht in het spectrum (kortere golflengte)?", opts: ["Ultraviolet (UV)", "Infrarood (IR)", "Radiogolven", "Microgolven"], ans: 0, pts: 2 },
    { q: "Elektromagnetische straling wordt gemaakt door...", opts: ["Elektronen die trillen in antenne of atoom", "Lucht die trilt", "Magneten die draaien", "Water dat stroomt"], ans: 0, pts: 2 },
    { q: "Wat staat in volgorde van kortste naar langste golflengte?", opts: ["Gamma → röntgen → UV → licht → IR → radio", "Radio → IR → licht → UV → röntgen → gamma", "Licht → UV → gamma → radio → IR", "UV → gamma → licht → IR → radio"], ans: 0, pts: 3 },
    { q: "Straling die geabsorbeerd wordt geeft energie af aan...", opts: ["Moleculen in het materiaal", "De lucht eromheen", "Het detectorscherm", "De röntgenbron"], ans: 0, pts: 2 },
    { q: "Wat is een kunstmatig radioactieve stof?", opts: ["Door de mens radioactief gemaakt", "Van nature radioactief", "Straling blokkerend", "Alleen in de zon voorkomend"], ans: 0, pts: 2 },
    { q: "Waarom kan gammastraling van een tracer buiten het lichaam gemeten worden?", opts: ["Gammastraling heeft groot doordringvermogen", "Gammastraling is zichtbaar", "Het lichaam zendt het zelf uit", "De huid vangt het op"], ans: 0, pts: 3 },
    { q: "Wat zie je op een röntgenfoto van een arm met een botbreuk?", opts: ["Een witte lijn (breuk) in de witte botten", "Zwarte lijn in zwarte botten", "Rode vlek op het scherm", "Niets, botten zijn onzichtbaar"], ans: 0, pts: 2 },
  ],
  bonus: [
    { title: "JACKPOT", desc: "Trek de winnende kaart! +3 punten.", pts: 3, act: "pts" },
    { title: "DUBBELE SLAG", desc: "Twee punten extra voor jou.", pts: 2, act: "pts" },
    { title: "TROEFKAART", desc: "Jij speelt de troef. +2 punten.", pts: 2, act: "pts" },
    { title: "WILD CARD", desc: "Alles is mogelijk. +3 punten.", pts: 3, act: "pts" },
    { title: "EXTRA BEURT", desc: "Trek nog een kaart — jouw beurt gaat door.", pts: 0, act: "extra" },
    { title: "BONUSVRAAG", desc: "Trek direct een gratis vraagkaart.", pts: 0, act: "extravraag" },
  ],
  straf: [
    { title: "STRALING OVERBELASTING", desc: "Je hebt te veel straling ontvangen. -3 punten.", pts: -3, skipTurn: false },
    { title: "DOSIMETER ALARM", desc: "Je dosimeter slaat af. -2 punten.", pts: -2, skipTurn: false },
    { title: "QUARANTAINE", desc: "Je wordt in quarantaine geplaatst. -2 punten én sla je volgende beurt over!", pts: -2, skipTurn: true },
    { title: "RÖNTGENBRAND", desc: "Je hebt je verbrand aan de röntgenbron. -4 punten.", pts: -4, skipTurn: false },
    { title: "MEETFOUT", desc: "Slordig gemeten. -1 punt.", pts: -1, skipTurn: false },
    { title: "CONTAMINATIE", desc: "Gevaarlijke besmetting! -3 punten én sla je volgende beurt over!", pts: -3, skipTurn: true },
  ],
  risico: [
    { sit: "Je assistent vraagt of jij in de kamer blijft tijdens een röntgenfoto. Wat doe je?", c: ["Weigeren en buiten wachten", "Blijven voor de gezelligheid"], safe: 0 },
    { sit: "Een klasgenoot zegt: 'Röntgenstraling en licht hebben niets gemeen.' Wat antwoord je?", c: ["Corrigeren: beide zijn elektromagnetische straling", "Akkoord gaan"], safe: 0 },
    { sit: "Er staat een röntgenbron zonder behuizing op tafel. Wat doe je?", c: ["Melden bij leraar en afstand houden", "Even snel kijken wat het is"], safe: 0 },
    { sit: "Een klasgenoot vraagt: 'Is röntgenstraling gevaarlijk?' Wat zeg je?", c: ["Geabsorbeerde straling kan schade geven, kleine doses zijn doorgaans veilig", "Helemaal niet gevaarlijk"], safe: 0 },
    { sit: "Welke methode gebruik je om te zien hoe een orgaan functioneert?", c: ["Gammascan met tracer, laat functie zien", "Röntgenfoto, want die is scherper"], safe: 0 },
    { sit: "De golflengte van een straling is 700 nm. Wat voor straling is dit?", c: ["Rood zichtbaar licht", "Infraroodstraling"], safe: 0 },
  ],
  kennis: [
    { fact: "Het EM-spectrum loopt van gammastraling (kortste golflengte) tot radiogolven (langste). Zichtbaar licht zit er precies tussenin!", bonus: "extravraag" },
    { fact: "De lichtsnelheid is 3,0 × 10⁸ m/s in vacuüm — dat is 300.000 km per seconde! Alle elektromagnetische straling reist met deze snelheid.", bonus: "pt1" },
    { fact: "Op een röntgenfoto zijn botten WIT (absorberen veel) en zachte weefsels DONKER (laten straling door = transmissie).", bonus: "pt2" },
    { fact: "Een tracer zendt gammastraling uit vanuit het lichaam. Een gammacamera buiten het lichaam vangt die straling op en maakt er een beeld van.", bonus: "extravraag" },
    { fact: "Transmissie = doorlaten · Reflectie = terugkaatsen · Absorptie = opnemen. Dit zijn de drie mogelijkheden als straling op een materiaal valt.", bonus: "pt1" },
    { fact: "Formule: c = λ × f. Als golflengte (λ) kleiner wordt, wordt frequentie (f) groter. Röntgenstraling heeft hoge frequentie en korte golflengte.", bonus: "extrabonus" },
    { fact: "Straling die geabsorbeerd wordt geeft energie af aan moleculen — die kunnen kapotgaan. Dat maakt röntgen- en gammastraling gevaarlijk bij grote doses.", bonus: "pt2" },
    { fact: "Radioactieve stoffen kunnen NATUURLIJK zijn (altijd in de natuur aanwezig) of KUNSTMATIG (door de mens gemaakt).", bonus: "extravraag" },
  ],
} as const;

export type CardType = "vraag" | "risico" | "kennis" | "bonus" | "straf";
